name: Test & Lint

env:
  CACHED_DEPENDENCY_PATHS: |
    ${{ github.workspace }}/node_modules
    /home/runner/.cache/Cypress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
      - name: Compute dependency cache key  # Props to the Sentry folks.
        id: compute_lockfile_hash
        run: echo "::set-output name=hash::${{ hashFiles('package-lock.json') }}"
      - name: Check dependency cache
        uses: actions/cache@v2
        id: cache_dependencies
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ steps.compute_lockfile_hash.outputs.hash }}
      - name: Install dependencies.
        if: steps.cache_dependencies.outputs.cache-hit == ''
        run: npm ci
      - name: Lint code
        run: npm run lint
    outputs:
      dependency_cache_key: ${{ steps.compute_lockfile_hash.outputs.hash }}

  e2e_tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: lint
    env:
      VUE_APP_KEYCLOAK_URL: http://keycloak.127.0.0.1.nip.io:8085/auth
      VUE_APP_KEYCLOAK_AUTHZ_JS: /js/keycloak-authz.js
      VUE_APP_KEYCLOAK_JS: /js/keycloak.js
      CYPRESS_coverage: true
      NODE_ENV: e2e
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
      - name: Check dependency cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ needs.lint.outputs.dependency_cache_key }}
      - name: E2E tests ğŸ§ª
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e:ci
          browser: chrome
          install: false
      - name: Upload Screenshots ğŸ“¸
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/e2e/screenshots
      - name: Coverage Report ğŸ“
        run: npm run test:report
      - name: Coveralls ğŸ“’
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: E2E